In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn import preprocessing

In [2]:
data=pd.read_csv(r'C:\Users\kowsar\PycharmProjects\PycharmProjects\pythonProject\venv\Scripts\ghalb.csv')

In [3]:
h=data.head()
h

id  age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0   1   63    1   1       145   233    1        2      150      0      2.3   
1   2   67    1   4       160   286    0        2      108      1      1.5   
2   3   67    1   4       120   229    0        2      129      1      2.6   
3   4   37    1   3       130   250    0        0      187      0      3.5   
4   5   41    0   2       130   204    0        2      172      0      1.4   

   slope  
0      3  
1      2  
2      2  
3      3  
4      1

DATA CLEANING

In [5]:
data1=data.drop('id', axis=1)
data1[0:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope
0   63    1   1       145   233    1        2      150      0      2.3      3
1   67    1   4       160   286    0        2      108      1      1.5      2
2   67    1   4       120   229    0        2      129      1      2.6      2
3   37    1   3       130   250    0        0      187      0      3.5      3
4   41    0   2       130   204    0        2      172      0      1.4      1

In [6]:
data.isnull().sum()

id          0
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
dtype: int64

In [7]:
scaler= preprocessing.StandardScaler()
x_normal=scaler.fit(data1).transform(data1)
x_normal

array([[ 0.94872647,  0.68620244, -2.25177456, ..., -0.69663055,
         1.08733806,  2.27457861],
       [ 1.39200191,  0.68620244,  0.87798549, ...,  1.43548113,
         0.39718162,  0.64911323],
       [ 1.39200191,  0.68620244,  0.87798549, ...,  1.43548113,
         1.34614673,  0.64911323],
       ...,
       [ 0.28381332,  0.68620244,  0.87798549, ...,  1.43548113,
         0.13837295,  0.64911323],
       [ 0.28381332, -1.4572959 , -1.20852121, ..., -0.69663055,
        -0.89686172,  0.64911323],
       [-1.82174501,  0.68620244, -0.16526786, ..., -0.69663055,
        -0.89686172, -0.97635214]])

In [8]:
k_mean=KMeans(init= 'k-means++', n_clusters=6, n_init=12)
k_mean.fit(x_normal)

KMeans(n_clusters=6, n_init=12)

In [9]:
labels=k_mean.labels_
labels

array([1, 4, 4, 0, 2, 5, 0, 3, 0, 1, 0, 3, 1, 5, 1, 5, 0, 5, 2, 5, 0, 3,
       0, 0, 4, 2, 3, 0, 5, 4, 3, 1, 3, 0, 5, 5, 4, 4, 4, 1, 0, 5, 3, 1,
       3, 0, 5, 0, 3, 1, 2, 5, 5, 5, 4, 4, 5, 5, 0, 5, 4, 4, 4, 3, 0, 4,
       0, 5, 4, 0, 3, 1, 4, 5, 5, 3, 4, 3, 5, 4, 4, 2, 5, 1, 5, 5, 5, 2,
       2, 2, 0, 0, 0, 2, 3, 5, 4, 0, 5, 5, 5, 5, 3, 1, 0, 5, 5, 0, 4, 5,
       4, 1, 5, 1, 0, 5, 1, 2, 1, 0, 1, 3, 4, 4, 1, 2, 1, 4, 5, 2, 0, 5,
       5, 5, 2, 2, 4, 0, 4, 1, 5, 3, 5, 4, 4, 5, 1, 5, 5, 2, 1, 2, 3, 4,
       4, 0, 5, 5, 0, 5, 5, 3, 2, 2, 5, 5, 5, 1, 5, 2, 4, 4, 4, 3, 0, 4,
       1, 4, 5, 1, 5, 3, 5, 0, 3, 2, 1, 4, 3, 0, 5, 4, 1, 1, 0, 4, 1, 2,
       2, 3, 2, 3, 1, 3, 5, 4, 4, 4, 5, 4, 2, 5, 5, 1, 5, 0, 2, 2, 0, 5,
       2, 2, 2, 4, 4, 2, 5, 3, 4, 4, 2, 4, 5, 3, 2, 4, 1, 5, 2, 5, 5, 2,
       2, 0, 1, 0, 5, 4, 5, 1, 4, 0, 4, 2, 5, 2, 2, 0, 3, 5, 2, 3, 3, 5,
       4, 4, 1, 1, 5, 5, 4, 0, 4, 0, 5, 0, 3, 2, 5, 2, 4, 5, 4, 5, 5, 0,
       1, 0, 5, 0, 0, 3, 4, 4, 4, 5, 1, 4, 5, 1, 4,

In [10]:
cluster_center=k_mean.cluster_centers_
cluster_center

array([[ 6.40360950e-01,  2.20224539e-01, -9.72295954e-02,
         1.17872526e-01, -1.82891887e-01, -4.17634535e-01,
         2.28818959e-01, -4.04501672e-01, -6.50280292e-01,
         7.46010689e-01,  8.96466661e-01],
       [ 3.36306460e-01,  2.34939630e-01,  5.43644268e-02,
         5.08905139e-01, -1.00972008e-01,  2.39443800e+00,
         2.21907860e-01, -1.47584424e-01,  2.01100684e-01,
         1.40643202e-01,  3.49685403e-01],
       [-6.47592810e-01, -1.45729590e+00, -1.65267857e-01,
        -5.23017227e-01, -3.04052064e-01, -4.17634535e-01,
        -1.81788078e-01,  4.12333328e-01, -5.44336855e-01,
        -5.80540012e-01, -2.41022565e-01],
       [ 8.47982054e-01, -1.06756893e+00, -4.18177760e-01,
         6.95438143e-01,  1.39764672e+00, -7.67772579e-02,
         2.84526605e-01,  3.17079867e-01, -3.73583323e-01,
        -3.63559009e-01, -6.31556453e-01],
       [ 2.26616485e-01,  3.40476900e-01,  7.60198824e-01,
        -1.62080536e-03,  2.81749676e-03, -4.17634535e-01,
  

In [11]:
data1['cluster_kmean']=labels

In [12]:
l=data1.head()
l

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   cluster_kmean  
0              1  
1              4  
2              4  
3              0  
4              2

In [13]:
e=data1['cluster_kmean'].value_counts()
e

cluster_kmean
5    82
4    62
0    46
2    42
1    38
3    33
Name: count, dtype: int64

In [14]:
data1.groupby('cluster_kmean').mean()

age       sex        cp    trestbps        chol  \
cluster_kmean                                                          
0              60.217391  0.782609  3.065217  133.760870  237.239130   
1              57.473684  0.789474  3.210526  140.631579  241.473684   
2              48.595238  0.000000  3.000000  122.500000  230.976190   
3              62.090909  0.181818  2.757576  143.909091  318.939394   
4              56.483871  0.838710  3.887097  131.661290  246.838710   
5              48.158537  1.000000  2.878049  126.195122  233.280488   

                    fbs   restecg     thalach     exang   oldpeak     slope  
cluster_kmean                                                                
0              0.000000  1.217391  140.369565  0.021739  1.904348  2.152174  
1              1.000000  1.210526  146.236842  0.421053  1.202632  1.815789  
2              0.000000  0.809524  159.023810  0.071429  0.366667  1.452381  
3              0.121212  1.272727  156.848485  0.151515  0.618182  1.212121  
4              0.000000  1.064516  127.661290  1.000000  1.820968  2.000000  
5              0.036585  0.682927  165.207317  0.146341  0.402439  1.121951